language: julia

os:
    - linux

julia:
    - 0.7
    - 1.0
    - nightly

script:
    - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Tensors", rev="master"));
                           Pkg.develop(PackageSpec(path=pwd()));
                           Pkg.build("FEMBasis");
                           Pkg.test("FEMBasis"; coverage=true)'

after_success:
    - julia -e 'cd(Pkg.dir("FEMBasis")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
